const emojiList = [
	{
		emoji: '😀',
		description: 'grinning face',
		category: 'Smileys & Emotion',
		aliases: ['grinning'],
		tags: ['smile', 'happy'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😃',
		description: 'grinning face with big eyes',
		category: 'Smileys & Emotion',
		aliases: ['smiley'],
		tags: ['happy', 'joy', 'haha'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😄',
		description: 'grinning face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['smile'],
		tags: ['happy', 'joy', 'laugh', 'pleased'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😁',
		description: 'beaming face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['grin'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😆',
		description: 'grinning squinting face',
		category: 'Smileys & Emotion',
		aliases: ['laughing', 'satisfied'],
		tags: ['happy', 'haha'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😅',
		description: 'grinning face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['sweat_smile'],
		tags: ['hot'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤣',
		description: 'rolling on the floor laughing',
		category: 'Smileys & Emotion',
		aliases: ['rofl'],
		tags: ['lol', 'laughing'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '😂',
		description: 'face with tears of joy',
		category: 'Smileys & Emotion',
		aliases: ['joy'],
		tags: ['tears'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙂',
		description: 'slightly smiling face',
		category: 'Smileys & Emotion',
		aliases: ['slightly_smiling_face'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '🙃',
		description: 'upside-down face',
		category: 'Smileys & Emotion',
		aliases: ['upside_down_face'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😉',
		description: 'winking face',
		category: 'Smileys & Emotion',
		aliases: ['wink'],
		tags: ['flirt'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😊',
		description: 'smiling face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['blush'],
		tags: ['proud'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😇',
		description: 'smiling face with halo',
		category: 'Smileys & Emotion',
		aliases: ['innocent'],
		tags: ['angel'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🥰',
		description: 'smiling face with hearts',
		category: 'Smileys & Emotion',
		aliases: ['smiling_face_with_three_hearts'],
		tags: ['love'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😍',
		description: 'smiling face with heart-eyes',
		category: 'Smileys & Emotion',
		aliases: ['heart_eyes'],
		tags: ['love', 'crush'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤩',
		description: 'star-struck',
		category: 'Smileys & Emotion',
		aliases: ['star_struck'],
		tags: ['eyes'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😘',
		description: 'face blowing a kiss',
		category: 'Smileys & Emotion',
		aliases: ['kissing_heart'],
		tags: ['flirt'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😗',
		description: 'kissing face',
		category: 'Smileys & Emotion',
		aliases: ['kissing'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '☺️',
		description: 'smiling face',
		category: 'Smileys & Emotion',
		aliases: ['relaxed'],
		tags: ['blush', 'pleased'],
		unicode_version: '',
		ios_version: '6.0',
	},
	{
		emoji: '😚',
		description: 'kissing face with closed eyes',
		category: 'Smileys & Emotion',
		aliases: ['kissing_closed_eyes'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😙',
		description: 'kissing face with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['kissing_smiling_eyes'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '🥲',
		description: 'smiling face with tear',
		category: 'Smileys & Emotion',
		aliases: ['smiling_face_with_tear'],
		tags: [],
		unicode_version: '13.0',
		ios_version: '14.0',
	},
	{
		emoji: '😋',
		description: 'face savoring food',
		category: 'Smileys & Emotion',
		aliases: ['yum'],
		tags: ['tongue', 'lick'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😛',
		description: 'face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😜',
		description: 'winking face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue_winking_eye'],
		tags: ['prank', 'silly'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤪',
		description: 'zany face',
		category: 'Smileys & Emotion',
		aliases: ['zany_face'],
		tags: ['goofy', 'wacky'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😝',
		description: 'squinting face with tongue',
		category: 'Smileys & Emotion',
		aliases: ['stuck_out_tongue_closed_eyes'],
		tags: ['prank'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤑',
		description: 'money-mouth face',
		category: 'Smileys & Emotion',
		aliases: ['money_mouth_face'],
		tags: ['rich'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤗',
		description: 'hugging face',
		category: 'Smileys & Emotion',
		aliases: ['hugs'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤭',
		description: 'face with hand over mouth',
		category: 'Smileys & Emotion',
		aliases: ['hand_over_mouth'],
		tags: ['quiet', 'whoops'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤫',
		description: 'shushing face',
		category: 'Smileys & Emotion',
		aliases: ['shushing_face'],
		tags: ['silence', 'quiet'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤔',
		description: 'thinking face',
		category: 'Smileys & Emotion',
		aliases: ['thinking'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤐',
		description: 'zipper-mouth face',
		category: 'Smileys & Emotion',
		aliases: ['zipper_mouth_face'],
		tags: ['silence', 'hush'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤨',
		description: 'face with raised eyebrow',
		category: 'Smileys & Emotion',
		aliases: ['raised_eyebrow'],
		tags: ['suspicious'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😐',
		description: 'neutral face',
		category: 'Smileys & Emotion',
		aliases: ['neutral_face'],
		tags: ['meh'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😑',
		description: 'expressionless face',
		category: 'Smileys & Emotion',
		aliases: ['expressionless'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😶',
		description: 'face without mouth',
		category: 'Smileys & Emotion',
		aliases: ['no_mouth'],
		tags: ['mute', 'silence'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😶‍🌫️',
		description: 'face in clouds',
		category: 'Smileys & Emotion',
		aliases: ['face_in_clouds'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
	},
	{
		emoji: '😏',
		description: 'smirking face',
		category: 'Smileys & Emotion',
		aliases: ['smirk'],
		tags: ['smug'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😒',
		description: 'unamused face',
		category: 'Smileys & Emotion',
		aliases: ['unamused'],
		tags: ['meh'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙄',
		description: 'face with rolling eyes',
		category: 'Smileys & Emotion',
		aliases: ['roll_eyes'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😬',
		description: 'grimacing face',
		category: 'Smileys & Emotion',
		aliases: ['grimacing'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😮‍💨',
		description: 'face exhaling',
		category: 'Smileys & Emotion',
		aliases: ['face_exhaling'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
	},
	{
		emoji: '🤥',
		description: 'lying face',
		category: 'Smileys & Emotion',
		aliases: ['lying_face'],
		tags: ['liar'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '😌',
		description: 'relieved face',
		category: 'Smileys & Emotion',
		aliases: ['relieved'],
		tags: ['whew'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😔',
		description: 'pensive face',
		category: 'Smileys & Emotion',
		aliases: ['pensive'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😪',
		description: 'sleepy face',
		category: 'Smileys & Emotion',
		aliases: ['sleepy'],
		tags: ['tired'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤤',
		description: 'drooling face',
		category: 'Smileys & Emotion',
		aliases: ['drooling_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '😴',
		description: 'sleeping face',
		category: 'Smileys & Emotion',
		aliases: ['sleeping'],
		tags: ['zzz'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😷',
		description: 'face with medical mask',
		category: 'Smileys & Emotion',
		aliases: ['mask'],
		tags: ['sick', 'ill'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤒',
		description: 'face with thermometer',
		category: 'Smileys & Emotion',
		aliases: ['face_with_thermometer'],
		tags: ['sick'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤕',
		description: 'face with head-bandage',
		category: 'Smileys & Emotion',
		aliases: ['face_with_head_bandage'],
		tags: ['hurt'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🤢',
		description: 'nauseated face',
		category: 'Smileys & Emotion',
		aliases: ['nauseated_face'],
		tags: ['sick', 'barf', 'disgusted'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🤮',
		description: 'face vomiting',
		category: 'Smileys & Emotion',
		aliases: ['vomiting_face'],
		tags: ['barf', 'sick'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤧',
		description: 'sneezing face',
		category: 'Smileys & Emotion',
		aliases: ['sneezing_face'],
		tags: ['achoo', 'sick'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🥵',
		description: 'hot face',
		category: 'Smileys & Emotion',
		aliases: ['hot_face'],
		tags: ['heat', 'sweating'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🥶',
		description: 'cold face',
		category: 'Smileys & Emotion',
		aliases: ['cold_face'],
		tags: ['freezing', 'ice'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🥴',
		description: 'woozy face',
		category: 'Smileys & Emotion',
		aliases: ['woozy_face'],
		tags: ['groggy'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😵',
		description: 'knocked-out face',
		category: 'Smileys & Emotion',
		aliases: ['dizzy_face'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😵‍💫',
		description: 'face with spiral eyes',
		category: 'Smileys & Emotion',
		aliases: ['face_with_spiral_eyes'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
	},
	{
		emoji: '🤯',
		description: 'exploding head',
		category: 'Smileys & Emotion',
		aliases: ['exploding_head'],
		tags: ['mind', 'blown'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🤠',
		description: 'cowboy hat face',
		category: 'Smileys & Emotion',
		aliases: ['cowboy_hat_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🥳',
		description: 'partying face',
		category: 'Smileys & Emotion',
		aliases: ['partying_face'],
		tags: ['celebration', 'birthday'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🥸',
		description: 'disguised face',
		category: 'Smileys & Emotion',
		aliases: ['disguised_face'],
		tags: [],
		unicode_version: '13.0',
		ios_version: '14.0',
	},
	{
		emoji: '😎',
		description: 'smiling face with sunglasses',
		category: 'Smileys & Emotion',
		aliases: ['sunglasses'],
		tags: ['cool'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤓',
		description: 'nerd face',
		category: 'Smileys & Emotion',
		aliases: ['nerd_face'],
		tags: ['geek', 'glasses'],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '🧐',
		description: 'face with monocle',
		category: 'Smileys & Emotion',
		aliases: ['monocle_face'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😕',
		description: 'confused face',
		category: 'Smileys & Emotion',
		aliases: ['confused'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😟',
		description: 'worried face',
		category: 'Smileys & Emotion',
		aliases: ['worried'],
		tags: ['nervous'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '🙁',
		description: 'slightly frowning face',
		category: 'Smileys & Emotion',
		aliases: ['slightly_frowning_face'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '☹️',
		description: 'frowning face',
		category: 'Smileys & Emotion',
		aliases: ['frowning_face'],
		tags: [],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '😮',
		description: 'face with open mouth',
		category: 'Smileys & Emotion',
		aliases: ['open_mouth'],
		tags: ['surprise', 'impressed', 'wow'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😯',
		description: 'hushed face',
		category: 'Smileys & Emotion',
		aliases: ['hushed'],
		tags: ['silence', 'speechless'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😲',
		description: 'astonished face',
		category: 'Smileys & Emotion',
		aliases: ['astonished'],
		tags: ['amazed', 'gasp'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😳',
		description: 'flushed face',
		category: 'Smileys & Emotion',
		aliases: ['flushed'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🥺',
		description: 'pleading face',
		category: 'Smileys & Emotion',
		aliases: ['pleading_face'],
		tags: ['puppy', 'eyes'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😦',
		description: 'frowning face with open mouth',
		category: 'Smileys & Emotion',
		aliases: ['frowning'],
		tags: [],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😧',
		description: 'anguished face',
		category: 'Smileys & Emotion',
		aliases: ['anguished'],
		tags: ['stunned'],
		unicode_version: '6.1',
		ios_version: '6.0',
	},
	{
		emoji: '😨',
		description: 'fearful face',
		category: 'Smileys & Emotion',
		aliases: ['fearful'],
		tags: ['scared', 'shocked', 'oops'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😰',
		description: 'anxious face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['cold_sweat'],
		tags: ['nervous'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😥',
		description: 'sad but relieved face',
		category: 'Smileys & Emotion',
		aliases: ['disappointed_relieved'],
		tags: ['phew', 'sweat', 'nervous'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😢',
		description: 'crying face',
		category: 'Smileys & Emotion',
		aliases: ['cry'],
		tags: ['sad', 'tear'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😭',
		description: 'loudly crying face',
		category: 'Smileys & Emotion',
		aliases: ['sob'],
		tags: ['sad', 'cry', 'bawling'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😱',
		description: 'face screaming in fear',
		category: 'Smileys & Emotion',
		aliases: ['scream'],
		tags: ['horror', 'shocked'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😖',
		description: 'confounded face',
		category: 'Smileys & Emotion',
		aliases: ['confounded'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😣',
		description: 'persevering face',
		category: 'Smileys & Emotion',
		aliases: ['persevere'],
		tags: ['struggling'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😞',
		description: 'disappointed face',
		category: 'Smileys & Emotion',
		aliases: ['disappointed'],
		tags: ['sad'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😓',
		description: 'downcast face with sweat',
		category: 'Smileys & Emotion',
		aliases: ['sweat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😩',
		description: 'weary face',
		category: 'Smileys & Emotion',
		aliases: ['weary'],
		tags: ['tired'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😫',
		description: 'tired face',
		category: 'Smileys & Emotion',
		aliases: ['tired_face'],
		tags: ['upset', 'whine'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🥱',
		description: 'yawning face',
		category: 'Smileys & Emotion',
		aliases: ['yawning_face'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '😤',
		description: 'face with steam from nose',
		category: 'Smileys & Emotion',
		aliases: ['triumph'],
		tags: ['smug'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😡',
		description: 'pouting face',
		category: 'Smileys & Emotion',
		aliases: ['rage', 'pout'],
		tags: ['angry'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😠',
		description: 'angry face',
		category: 'Smileys & Emotion',
		aliases: ['angry'],
		tags: ['mad', 'annoyed'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤬',
		description: 'face with symbols on mouth',
		category: 'Smileys & Emotion',
		aliases: ['cursing_face'],
		tags: ['foul'],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '😈',
		description: 'smiling face with horns',
		category: 'Smileys & Emotion',
		aliases: ['smiling_imp'],
		tags: ['devil', 'evil', 'horns'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👿',
		description: 'angry face with horns',
		category: 'Smileys & Emotion',
		aliases: ['imp'],
		tags: ['angry', 'devil', 'evil', 'horns'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💀',
		description: 'skull',
		category: 'Smileys & Emotion',
		aliases: ['skull'],
		tags: ['dead', 'danger', 'poison'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '☠️',
		description: 'skull and crossbones',
		category: 'Smileys & Emotion',
		aliases: ['skull_and_crossbones'],
		tags: ['danger', 'pirate'],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '💩',
		description: 'pile of poo',
		category: 'Smileys & Emotion',
		aliases: ['hankey', 'poop', 'shit'],
		tags: ['crap'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤡',
		description: 'clown face',
		category: 'Smileys & Emotion',
		aliases: ['clown_face'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '👹',
		description: 'ogre',
		category: 'Smileys & Emotion',
		aliases: ['japanese_ogre'],
		tags: ['monster'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👺',
		description: 'goblin',
		category: 'Smileys & Emotion',
		aliases: ['japanese_goblin'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👻',
		description: 'ghost',
		category: 'Smileys & Emotion',
		aliases: ['ghost'],
		tags: ['halloween'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👽',
		description: 'alien',
		category: 'Smileys & Emotion',
		aliases: ['alien'],
		tags: ['ufo'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👾',
		description: 'alien monster',
		category: 'Smileys & Emotion',
		aliases: ['space_invader'],
		tags: ['game', 'retro'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤖',
		description: 'robot',
		category: 'Smileys & Emotion',
		aliases: ['robot'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
	},
	{
		emoji: '😺',
		description: 'grinning cat',
		category: 'Smileys & Emotion',
		aliases: ['smiley_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😸',
		description: 'grinning cat with smiling eyes',
		category: 'Smileys & Emotion',
		aliases: ['smile_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😹',
		description: 'cat with tears of joy',
		category: 'Smileys & Emotion',
		aliases: ['joy_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😻',
		description: 'smiling cat with heart-eyes',
		category: 'Smileys & Emotion',
		aliases: ['heart_eyes_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😼',
		description: 'cat with wry smile',
		category: 'Smileys & Emotion',
		aliases: ['smirk_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😽',
		description: 'kissing cat',
		category: 'Smileys & Emotion',
		aliases: ['kissing_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙀',
		description: 'weary cat',
		category: 'Smileys & Emotion',
		aliases: ['scream_cat'],
		tags: ['horror'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😿',
		description: 'crying cat',
		category: 'Smileys & Emotion',
		aliases: ['crying_cat_face'],
		tags: ['sad', 'tear'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '😾',
		description: 'pouting cat',
		category: 'Smileys & Emotion',
		aliases: ['pouting_cat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙈',
		description: 'see-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['see_no_evil'],
		tags: ['monkey', 'blind', 'ignore'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙉',
		description: 'hear-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['hear_no_evil'],
		tags: ['monkey', 'deaf'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🙊',
		description: 'speak-no-evil monkey',
		category: 'Smileys & Emotion',
		aliases: ['speak_no_evil'],
		tags: ['monkey', 'mute', 'hush'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💋',
		description: 'kiss mark',
		category: 'Smileys & Emotion',
		aliases: ['kiss'],
		tags: ['lipstick'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💌',
		description: 'love letter',
		category: 'Smileys & Emotion',
		aliases: ['love_letter'],
		tags: ['email', 'envelope'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💘',
		description: 'heart with arrow',
		category: 'Smileys & Emotion',
		aliases: ['cupid'],
		tags: ['love', 'heart'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💝',
		description: 'heart with ribbon',
		category: 'Smileys & Emotion',
		aliases: ['gift_heart'],
		tags: ['chocolates'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💖',
		description: 'sparkling heart',
		category: 'Smileys & Emotion',
		aliases: ['sparkling_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💗',
		description: 'growing heart',
		category: 'Smileys & Emotion',
		aliases: ['heartpulse'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💓',
		description: 'beating heart',
		category: 'Smileys & Emotion',
		aliases: ['heartbeat'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💞',
		description: 'revolving hearts',
		category: 'Smileys & Emotion',
		aliases: ['revolving_hearts'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💕',
		description: 'two hearts',
		category: 'Smileys & Emotion',
		aliases: ['two_hearts'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💟',
		description: 'heart decoration',
		category: 'Smileys & Emotion',
		aliases: ['heart_decoration'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '❣️',
		description: 'heart exclamation',
		category: 'Smileys & Emotion',
		aliases: ['heavy_heart_exclamation'],
		tags: [],
		unicode_version: '',
		ios_version: '9.1',
	},
	{
		emoji: '💔',
		description: 'broken heart',
		category: 'Smileys & Emotion',
		aliases: ['broken_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '❤️‍🔥',
		description: 'heart on fire',
		category: 'Smileys & Emotion',
		aliases: ['heart_on_fire'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
	},
	{
		emoji: '❤️‍🩹',
		description: 'mending heart',
		category: 'Smileys & Emotion',
		aliases: ['mending_heart'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
	},
	{
		emoji: '❤️',
		description: 'red heart',
		category: 'Smileys & Emotion',
		aliases: ['heart'],
		tags: ['love'],
		unicode_version: '',
		ios_version: '6.0',
	},
	{
		emoji: '🧡',
		description: 'orange heart',
		category: 'Smileys & Emotion',
		aliases: ['orange_heart'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '💛',
		description: 'yellow heart',
		category: 'Smileys & Emotion',
		aliases: ['yellow_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💚',
		description: 'green heart',
		category: 'Smileys & Emotion',
		aliases: ['green_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💙',
		description: 'blue heart',
		category: 'Smileys & Emotion',
		aliases: ['blue_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💜',
		description: 'purple heart',
		category: 'Smileys & Emotion',
		aliases: ['purple_heart'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🤎',
		description: 'brown heart',
		category: 'Smileys & Emotion',
		aliases: ['brown_heart'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '🖤',
		description: 'black heart',
		category: 'Smileys & Emotion',
		aliases: ['black_heart'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🤍',
		description: 'white heart',
		category: 'Smileys & Emotion',
		aliases: ['white_heart'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '💯',
		description: 'hundred points',
		category: 'Smileys & Emotion',
		aliases: ['100'],
		tags: ['score', 'perfect'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💢',
		description: 'anger symbol',
		category: 'Smileys & Emotion',
		aliases: ['anger'],
		tags: ['angry'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💥',
		description: 'collision',
		category: 'Smileys & Emotion',
		aliases: ['boom', 'collision'],
		tags: ['explode'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💫',
		description: 'dizzy',
		category: 'Smileys & Emotion',
		aliases: ['dizzy'],
		tags: ['star'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💦',
		description: 'sweat droplets',
		category: 'Smileys & Emotion',
		aliases: ['sweat_drops'],
		tags: ['water', 'workout'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💨',
		description: 'dashing away',
		category: 'Smileys & Emotion',
		aliases: ['dash'],
		tags: ['wind', 'blow', 'fast'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '🕳️',
		description: 'hole',
		category: 'Smileys & Emotion',
		aliases: ['hole'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '💣',
		description: 'bomb',
		category: 'Smileys & Emotion',
		aliases: ['bomb'],
		tags: ['boom'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💬',
		description: 'speech balloon',
		category: 'Smileys & Emotion',
		aliases: ['speech_balloon'],
		tags: ['comment'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👁️‍🗨️',
		description: 'eye in speech bubble',
		category: 'Smileys & Emotion',
		aliases: ['eye_speech_bubble'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🗨️',
		description: 'left speech bubble',
		category: 'Smileys & Emotion',
		aliases: ['left_speech_bubble'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🗯️',
		description: 'right anger bubble',
		category: 'Smileys & Emotion',
		aliases: ['right_anger_bubble'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '💭',
		description: 'thought balloon',
		category: 'Smileys & Emotion',
		aliases: ['thought_balloon'],
		tags: ['thinking'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '💤',
		description: 'zzz',
		category: 'Smileys & Emotion',
		aliases: ['zzz'],
		tags: ['sleeping'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👋',
		description: 'waving hand',
		category: 'People & Body',
		aliases: ['wave'],
		tags: ['goodbye'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤚',
		description: 'raised back of hand',
		category: 'People & Body',
		aliases: ['raised_back_of_hand'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '🖐️',
		description: 'hand with fingers splayed',
		category: 'People & Body',
		aliases: ['raised_hand_with_fingers_splayed'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
		skin_tones: !0,
	},
	{
		emoji: '✋',
		description: 'raised hand',
		category: 'People & Body',
		aliases: ['hand', 'raised_hand'],
		tags: ['highfive', 'stop'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🖖',
		description: 'vulcan salute',
		category: 'People & Body',
		aliases: ['vulcan_salute'],
		tags: ['prosper', 'spock'],
		unicode_version: '7.0',
		ios_version: '8.3',
		skin_tones: !0,
	},
	{
		emoji: '👌',
		description: 'OK hand',
		category: 'People & Body',
		aliases: ['ok_hand'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤌',
		description: 'pinched fingers',
		category: 'People & Body',
		aliases: ['pinched_fingers'],
		tags: [],
		unicode_version: '13.0',
		ios_version: '14.0',
		skin_tones: !0,
	},
	{
		emoji: '🤏',
		description: 'pinching hand',
		category: 'People & Body',
		aliases: ['pinching_hand'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
		skin_tones: !0,
	},
	{
		emoji: '✌️',
		description: 'victory hand',
		category: 'People & Body',
		aliases: ['v'],
		tags: ['victory', 'peace'],
		unicode_version: '',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤞',
		description: 'crossed fingers',
		category: 'People & Body',
		aliases: ['crossed_fingers'],
		tags: ['luck', 'hopeful'],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '🤟',
		description: 'love-you gesture',
		category: 'People & Body',
		aliases: ['love_you_gesture'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🤘',
		description: 'sign of the horns',
		category: 'People & Body',
		aliases: ['metal'],
		tags: [],
		unicode_version: '8.0',
		ios_version: '9.1',
		skin_tones: !0,
	},
	{
		emoji: '🤙',
		description: 'call me hand',
		category: 'People & Body',
		aliases: ['call_me_hand'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '👈',
		description: 'backhand index pointing left',
		category: 'People & Body',
		aliases: ['point_left'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👉',
		description: 'backhand index pointing right',
		category: 'People & Body',
		aliases: ['point_right'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👆',
		description: 'backhand index pointing up',
		category: 'People & Body',
		aliases: ['point_up_2'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🖕',
		description: 'middle finger',
		category: 'People & Body',
		aliases: ['middle_finger', 'fu'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
		skin_tones: !0,
	},
	{
		emoji: '👇',
		description: 'backhand index pointing down',
		category: 'People & Body',
		aliases: ['point_down'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '☝️',
		description: 'index pointing up',
		category: 'People & Body',
		aliases: ['point_up'],
		tags: [],
		unicode_version: '',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👍',
		description: 'thumbs up',
		category: 'People & Body',
		aliases: ['+1', 'thumbsup'],
		tags: ['approve', 'ok'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👎',
		description: 'thumbs down',
		category: 'People & Body',
		aliases: ['-1', 'thumbsdown'],
		tags: ['disapprove', 'bury'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '✊',
		description: 'raised fist',
		category: 'People & Body',
		aliases: ['fist_raised', 'fist'],
		tags: ['power'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👊',
		description: 'oncoming fist',
		category: 'People & Body',
		aliases: ['fist_oncoming', 'facepunch', 'punch'],
		tags: ['attack'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤛',
		description: 'left-facing fist',
		category: 'People & Body',
		aliases: ['fist_left'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '🤜',
		description: 'right-facing fist',
		category: 'People & Body',
		aliases: ['fist_right'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '👏',
		description: 'clapping hands',
		category: 'People & Body',
		aliases: ['clap'],
		tags: ['praise', 'applause'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🙌',
		description: 'raising hands',
		category: 'People & Body',
		aliases: ['raised_hands'],
		tags: ['hooray'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👐',
		description: 'open hands',
		category: 'People & Body',
		aliases: ['open_hands'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤲',
		description: 'palms up together',
		category: 'People & Body',
		aliases: ['palms_up_together'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🤝',
		description: 'handshake',
		category: 'People & Body',
		aliases: ['handshake'],
		tags: ['deal'],
		unicode_version: '9.0',
		ios_version: '10.2',
	},
	{
		emoji: '🙏',
		description: 'folded hands',
		category: 'People & Body',
		aliases: ['pray'],
		tags: ['please', 'hope', 'wish'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '✍️',
		description: 'writing hand',
		category: 'People & Body',
		aliases: ['writing_hand'],
		tags: [],
		unicode_version: '',
		ios_version: '9.1',
		skin_tones: !0,
	},
	{
		emoji: '💅',
		description: 'nail polish',
		category: 'People & Body',
		aliases: ['nail_care'],
		tags: ['beauty', 'manicure'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🤳',
		description: 'selfie',
		category: 'People & Body',
		aliases: ['selfie'],
		tags: [],
		unicode_version: '9.0',
		ios_version: '10.2',
		skin_tones: !0,
	},
	{
		emoji: '💪',
		description: 'flexed biceps',
		category: 'People & Body',
		aliases: ['muscle'],
		tags: ['flex', 'bicep', 'strong', 'workout'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🦾',
		description: 'mechanical arm',
		category: 'People & Body',
		aliases: ['mechanical_arm'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '🦿',
		description: 'mechanical leg',
		category: 'People & Body',
		aliases: ['mechanical_leg'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
	},
	{
		emoji: '🦵',
		description: 'leg',
		category: 'People & Body',
		aliases: ['leg'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🦶',
		description: 'foot',
		category: 'People & Body',
		aliases: ['foot'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👂',
		description: 'ear',
		category: 'People & Body',
		aliases: ['ear'],
		tags: ['hear', 'sound', 'listen'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🦻',
		description: 'ear with hearing aid',
		category: 'People & Body',
		aliases: ['ear_with_hearing_aid'],
		tags: [],
		unicode_version: '12.0',
		ios_version: '13.0',
		skin_tones: !0,
	},
	{
		emoji: '👃',
		description: 'nose',
		category: 'People & Body',
		aliases: ['nose'],
		tags: ['smell'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🧠',
		description: 'brain',
		category: 'People & Body',
		aliases: ['brain'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🫀',
		description: 'anatomical heart',
		category: 'People & Body',
		aliases: ['anatomical_heart'],
		tags: [],
		unicode_version: '13.0',
		ios_version: '14.0',
	},
	{
		emoji: '🫁',
		description: 'lungs',
		category: 'People & Body',
		aliases: ['lungs'],
		tags: [],
		unicode_version: '13.0',
		ios_version: '14.0',
	},
	{
		emoji: '🦷',
		description: 'tooth',
		category: 'People & Body',
		aliases: ['tooth'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '🦴',
		description: 'bone',
		category: 'People & Body',
		aliases: ['bone'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
	},
	{
		emoji: '👀',
		description: 'eyes',
		category: 'People & Body',
		aliases: ['eyes'],
		tags: ['look', 'see', 'watch'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👁️',
		description: 'eye',
		category: 'People & Body',
		aliases: ['eye'],
		tags: [],
		unicode_version: '7.0',
		ios_version: '9.1',
	},
	{
		emoji: '👅',
		description: 'tongue',
		category: 'People & Body',
		aliases: ['tongue'],
		tags: ['taste'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👄',
		description: 'mouth',
		category: 'People & Body',
		aliases: ['lips'],
		tags: ['kiss'],
		unicode_version: '6.0',
		ios_version: '6.0',
	},
	{
		emoji: '👶',
		description: 'baby',
		category: 'People & Body',
		aliases: ['baby'],
		tags: ['child', 'newborn'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🧒',
		description: 'child',
		category: 'People & Body',
		aliases: ['child'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👦',
		description: 'boy',
		category: 'People & Body',
		aliases: ['boy'],
		tags: ['child'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👧',
		description: 'girl',
		category: 'People & Body',
		aliases: ['girl'],
		tags: ['child'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🧑',
		description: 'person',
		category: 'People & Body',
		aliases: ['adult'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👱',
		description: 'person: blond hair',
		category: 'People & Body',
		aliases: ['blond_haired_person'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👨',
		description: 'man',
		category: 'People & Body',
		aliases: ['man'],
		tags: ['mustache', 'father', 'dad'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '🧔',
		description: 'person: beard',
		category: 'People & Body',
		aliases: ['bearded_person'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧔‍♂️',
		description: 'man: beard',
		category: 'People & Body',
		aliases: ['man_beard'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
		skin_tones: !0,
	},
	{
		emoji: '🧔‍♀️',
		description: 'woman: beard',
		category: 'People & Body',
		aliases: ['woman_beard'],
		tags: [],
		unicode_version: '13.1',
		ios_version: '14.0',
		skin_tones: !0,
	},
	{
		emoji: '👨‍🦰',
		description: 'man: red hair',
		category: 'People & Body',
		aliases: ['red_haired_man'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👨‍🦱',
		description: 'man: curly hair',
		category: 'People & Body',
		aliases: ['curly_haired_man'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👨‍🦳',
		description: 'man: white hair',
		category: 'People & Body',
		aliases: ['white_haired_man'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👨‍🦲',
		description: 'man: bald',
		category: 'People & Body',
		aliases: ['bald_man'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👩',
		description: 'woman',
		category: 'People & Body',
		aliases: ['woman'],
		tags: ['girls'],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
	{
		emoji: '👩‍🦰',
		description: 'woman: red hair',
		category: 'People & Body',
		aliases: ['red_haired_woman'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧑‍🦰',
		description: 'person: red hair',
		category: 'People & Body',
		aliases: ['person_red_hair'],
		tags: [],
		unicode_version: '12.1',
		ios_version: '13.2',
		skin_tones: !0,
	},
	{
		emoji: '👩‍🦱',
		description: 'woman: curly hair',
		category: 'People & Body',
		aliases: ['curly_haired_woman'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧑‍🦱',
		description: 'person: curly hair',
		category: 'People & Body',
		aliases: ['person_curly_hair'],
		tags: [],
		unicode_version: '12.1',
		ios_version: '13.2',
		skin_tones: !0,
	},
	{
		emoji: '👩‍🦳',
		description: 'woman: white hair',
		category: 'People & Body',
		aliases: ['white_haired_woman'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧑‍🦳',
		description: 'person: white hair',
		category: 'People & Body',
		aliases: ['person_white_hair'],
		tags: [],
		unicode_version: '12.1',
		ios_version: '13.2',
		skin_tones: !0,
	},
	{
		emoji: '👩‍🦲',
		description: 'woman: bald',
		category: 'People & Body',
		aliases: ['bald_woman'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧑‍🦲',
		description: 'person: bald',
		category: 'People & Body',
		aliases: ['person_bald'],
		tags: [],
		unicode_version: '12.1',
		ios_version: '13.2',
		skin_tones: !0,
	},
	{
		emoji: '👱‍♀️',
		description: 'woman: blond hair',
		category: 'People & Body',
		aliases: ['blond_haired_woman', 'blonde_woman'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '10.0',
		skin_tones: !0,
	},
	{
		emoji: '👱‍♂️',
		description: 'man: blond hair',
		category: 'People & Body',
		aliases: ['blond_haired_man'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '🧓',
		description: 'older person',
		category: 'People & Body',
		aliases: ['older_adult'],
		tags: [],
		unicode_version: '11.0',
		ios_version: '12.1',
		skin_tones: !0,
	},
	{
		emoji: '👴',
		description: 'old man',
		category: 'People & Body',
		aliases: ['older_man'],
		tags: [],
		unicode_version: '6.0',
		ios_version: '6.0',
		skin_tones: !0,
	},
]
